In [1]:
import pandas as pd

In [2]:
readData = pd.read_csv("vgchartz-2024.csv")

readData

,img,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date,last_update
0,/games/boxart/full_6510540AmericaFrontccc.jpg,Grand Theft Auto V,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,6.37,0.99,9.85,3.12,2013-09-17,NaN
1,/games/boxart/full_5563178AmericaFrontccc.jpg,Grand Theft Auto V,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,6.06,0.60,9.71,3.02,2014-11-18,2018-01-03
2,/games/boxart/827563ccc.jpg,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,8.41,0.47,5.49,1.78,2002-10-28,NaN
3,/games/boxart/full_9218923AmericaFrontccc.jpg,Grand Theft Auto V,X360,Action,Rockstar Games,Rockstar North,NaN,15.86,9.06,0.06,5.33,1.42,2013-09-17,NaN
4,/games/boxart/full_4990510AmericaFrontccc.jpg,Call of Duty: Black Ops 3,PS4,Shooter,Activision,Treyarch,8.1,15.09,6.18,0.41,6.05,2.44,2015-11-06,2018-01-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64011,/games/boxart/full_2779838AmericaFrontccc.jpg,XBlaze Lost: Memories,PC,Visual Novel,Aksys Games,Arc System Works,NaN,NaN,NaN,NaN,NaN,NaN,2016-08-11,2019-01-28
64012,/games/boxart/full_8031506AmericaFrontccc.jpg,"Yoru, Tomosu",PS4,Visual Novel,Nippon Ichi Software,Nippon Ichi Software,NaN,NaN,NaN,NaN,NaN,NaN,2020-07-30,2020-05-09
64013,/games/boxart/full_6553045AmericaFrontccc.jpg,"Yoru, Tomosu",NS,Visual Novel,Nippon Ichi Software,Nippon Ichi Software,NaN,NaN,NaN,NaN,NaN,NaN,2020-07-30,2020-05-09
64014,/games/boxart/full_6012940JapanFrontccc.png,Yunohana SpRING! ~Mellow Times~,NS,Visual Novel,Idea Factory,Otomate,NaN,NaN,NaN,NaN,NaN,NaN,2019-02-28,2019-02-24
64015,/games/boxart/default.jpg,Yurukill: The Calumniation Games,PS4,Visual Novel,Unknown,G.rev Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-09-29

In [3]:
readData.columns

Index(['img', 'title', 'console', 'genre', 'publisher', 'developer',
       'critic_score', 'total_sales', 'na_sales', 'jp_sales', 'pal_sales',
       'other_sales', 'release_date', 'last_update'],
      dtype='str')

In [4]:
readData.shape

(64016, 14)

In [5]:
readData.info()

<class 'pandas.DataFrame'>
RangeIndex: 64016 entries, 0 to 64015
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   img           64016 non-null  str
 1   title         64016 non-null  str
 2   console       64016 non-null  str
 3   genre         64016 non-null  str
 4   publisher     64016 non-null  str
 5   developer     63999 non-null  str
 6   critic_score  6678 non-null   float64
 7   total_sales   18922 non-null  float64
 8   na_sales      12637 non-null  float64
 9   jp_sales      6726 non-null   float64
 10  pal_sales     12824 non-null  float64
 11  other_sales   15128 non-null  float64
 12  release_date  56965 non-null  str
 13  last_update   17879 non-null  str
dtypes: float64(6), str(8)
memory usage: 6.8 MB

In [6]:
readData.describe()

,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales
count,6678.000000,18922.000000,12637.000000,6726.000000,12824.000000,15128.000000
mean,7.220440,0.349113,0.264740,0.102281,0.149472,0.043041
std,1.457066,0.807462,0.494787,0.168811,0.392653,0.126643
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,6.400000,0.030000,0.050000,0.020000,0.010000,0.000000
50%,7.500000,0.120000,0.120000,0.040000,0.040000,0.010000
75%,8.300000,0.340000,0.280000,0.120000,0.140000,0.030000
max,10.000000,20.320000,9.760000,2.130000,9.850000,3.120000

In [7]:
readData.columns

Index(['img', 'title', 'console', 'genre', 'publisher', 'developer',
       'critic_score', 'total_sales', 'na_sales', 'jp_sales', 'pal_sales',
       'other_sales', 'release_date', 'last_update'],
      dtype='str')

In [8]:
readData[['last_update' , 'total_sales', 'na_sales','title']]

# readData.from_arrow

      last_update  total_sales  na_sales                             title
0             NaN        20.32      6.37                Grand Theft Auto V
1      2018-01-03        19.39      6.06                Grand Theft Auto V
2             NaN        16.15      8.41       Grand Theft Auto: Vice City
3             NaN        15.86      9.06                Grand Theft Auto V
4      2018-01-14        15.09      6.18         Call of Duty: Black Ops 3
...           ...          ...       ...                               ...
64011  2019-01-28          NaN       NaN             XBlaze Lost: Memories
64012  2020-05-09          NaN       NaN                      Yoru, Tomosu
64013  2020-05-09          NaN       NaN                      Yoru, Tomosu
64014  2019-02-24          NaN       NaN   Yunohana SpRING! ~Mellow Times~
64015  2023-09-29          NaN       NaN  Yurukill: The Calumniation Games

[64016 rows x 4 columns]

In [9]:
acc = readData.iloc[1000 : 2000 , 6 : 9]

acc

      critic_score  total_sales  na_sales
1000           9.5         1.33      0.58
1001           NaN         1.33      0.74
1002           NaN         1.33      0.45
1003           7.9         1.33      0.92
1004           7.1         1.33      0.90
...            ...          ...       ...
1995           NaN         0.79      0.44
1996           NaN         0.79      0.35
1997           6.6         0.79      0.17
1998           8.2         0.79      0.61
1999           NaN         0.79      0.61

[1000 rows x 3 columns]

In [10]:
label = readData.loc[500 : 800 , ['last_update' , 'total_sales', 'na_sales','title']]

label

,last_update,total_sales,na_sales,title
500,NaN,2.05,0.75,Dark Souls
501,NaN,2.05,1.52,Mortal Kombat vs DC Universe
502,2018-09-15,2.05,0.74,The Elder Scrolls Online: Tamriel Unlimited
503,NaN,2.05,1.04,Need for Speed: ProStreet
504,NaN,2.05,1.75,NBA Jam
...,...,...,...,...
796,2018-01-12,1.52,0.58,Forza Motorsport 7
797,NaN,1.52,1.45,NASCAR 99
798,NaN,1.52,0.85,Disney Fairies: Tinker Bell
799,NaN,1.52,0.18,Xevious
800,NaN,1.52,0.94,Dead Space 2

In [11]:

readData

,img,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date,last_update
0,/games/boxart/full_6510540AmericaFrontccc.jpg,Grand Theft Auto V,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,6.37,0.99,9.85,3.12,2013-09-17,NaN
1,/games/boxart/full_5563178AmericaFrontccc.jpg,Grand Theft Auto V,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,6.06,0.60,9.71,3.02,2014-11-18,2018-01-03
2,/games/boxart/827563ccc.jpg,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,8.41,0.47,5.49,1.78,2002-10-28,NaN
3,/games/boxart/full_9218923AmericaFrontccc.jpg,Grand Theft Auto V,X360,Action,Rockstar Games,Rockstar North,NaN,15.86,9.06,0.06,5.33,1.42,2013-09-17,NaN
4,/games/boxart/full_4990510AmericaFrontccc.jpg,Call of Duty: Black Ops 3,PS4,Shooter,Activision,Treyarch,8.1,15.09,6.18,0.41,6.05,2.44,2015-11-06,2018-01-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64011,/games/boxart/full_2779838AmericaFrontccc.jpg,XBlaze Lost: Memories,PC,Visual Novel,Aksys Games,Arc System Works,NaN,NaN,NaN,NaN,NaN,NaN,2016-08-11,2019-01-28
64012,/games/boxart/full_8031506AmericaFrontccc.jpg,"Yoru, Tomosu",PS4,Visual Novel,Nippon Ichi Software,Nippon Ichi Software,NaN,NaN,NaN,NaN,NaN,NaN,2020-07-30,2020-05-09
64013,/games/boxart/full_6553045AmericaFrontccc.jpg,"Yoru, Tomosu",NS,Visual Novel,Nippon Ichi Software,Nippon Ichi Software,NaN,NaN,NaN,NaN,NaN,NaN,2020-07-30,2020-05-09
64014,/games/boxart/full_6012940JapanFrontccc.png,Yunohana SpRING! ~Mellow Times~,NS,Visual Novel,Idea Factory,Otomate,NaN,NaN,NaN,NaN,NaN,NaN,2019-02-28,2019-02-24
64015,/games/boxart/default.jpg,Yurukill: The Calumniation Games,PS4,Visual Novel,Unknown,G.rev Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-09-29

In [12]:
r_games = readData[(readData['publisher'].str.contains('Rockstar Games')) & (readData['genre'].str.contains("Action"))]

r_games

,img,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date,last_update
0,/games/boxart/full_6510540AmericaFrontccc.jpg,Grand Theft Auto V,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,6.37,0.99,9.85,3.12,2013-09-17,NaN
1,/games/boxart/full_5563178AmericaFrontccc.jpg,Grand Theft Auto V,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,6.06,0.60,9.71,3.02,2014-11-18,2018-01-03
2,/games/boxart/827563ccc.jpg,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,8.41,0.47,5.49,1.78,2002-10-28,NaN
3,/games/boxart/full_9218923AmericaFrontccc.jpg,Grand Theft Auto V,X360,Action,Rockstar Games,Rockstar North,NaN,15.86,9.06,0.06,5.33,1.42,2013-09-17,NaN
7,/games/boxart/full_4653215AmericaFrontccc.jpg,Red Dead Redemption 2,PS4,Action-Adventure,Rockstar Games,Rockstar Games,9.8,13.94,5.26,0.21,6.21,2.26,2018-10-26,2018-11-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29255,/games/boxart/full_2529513AmericaFrontccc.jpg,Manhunt,All,Action-Adventure,Rockstar Games,Rockstar North,NaN,NaN,NaN,NaN,NaN,NaN,2003-11-19,2021-04-02
29894,/games/boxart/full_8752476AmericaFrontccc.jpg,Grand Theft Auto V,PS5,Action-Adventure,Rockstar Games,Rockstar Games,NaN,NaN,NaN,NaN,NaN,NaN,2021-12-01,2020-06-11
29895,/games/boxart/full_915577AmericaFrontccc.jpg,Grand Theft Auto V,XS,Action-Adventure,Rockstar Games,Rockstar Games,NaN,NaN,NaN,NaN,NaN,NaN,2021-12-01,2020-06-12
29899,/games/boxart/full_8097252AmericaFrontccc.jpg,Grand Theft Auto: The Trilogy – The Definitive...,All,Action-Adventure,Rockstar Games,Grove Street Games,NaN,NaN,NaN,NaN,NaN,NaN,2021-11-11,2021-12-23
30184,/games/boxart/full_1544218AmericaFrontccc.jpg,Red Dead Redemption 2,PC,Action-Adventure,Rockstar Games,Rockstar Games,NaN,NaN,NaN,NaN,NaN,NaN,2019-11-05,2019-10-05

In [13]:
readData['genre'].unique()

<StringArray>
[          'Action',          'Shooter', 'Action-Adventure',
           'Sports',     'Role-Playing',       'Simulation',
           'Racing',            'Music',             'Misc',
         'Fighting',         'Platform',        'Adventure',
         'Strategy',           'Puzzle',              'MMO',
          'Sandbox',            'Party',        'Education',
       'Board Game',     'Visual Novel']
Length: 20, dtype: str

In [ ]:
dt["developer"].unique()